sources = Split("""array.c
					boolean.c
					character.c
					core.c
					float.c
					integer.c
					object.c
					string.c""")

CFLAGS = Split("""-ansi
					-Wall""")

LIBS = Split("""gc
				""")



Library('kitsune', sources,
		LIBS = LIBS,
		CFLAGS = CFLAGS)
