sources = Split("""expressions.c
					generator.c
					lexer.c
					main.c
					parser.c
					""")

CFLAGS = Split("""-ansi
					-Wall""")

LIBS = Split("""gc
				""")



Program('kitsunec', sources,
				LIBS = LIBS,
				CFLAGS = CFLAGS)
